name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x Flightwise/gradlew

    - name: Build with Gradle
      run: cd Flightwise && ./gradlew build

    - name: Assemble debug APK
      run: cd Flightwise && ./gradlew assembleDebug


  test:
    name: test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x Flightwise/gradlew

    - name: Run Unit Tests
      run: cd Flightwise && ./gradlew test --continue

    - name: Run Lint
      run: cd Flightwise && ./gradlew lint

    - name: Run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        arch: x86_64
        profile: Nexus 6
        script: cd Flightwise && ./gradlew connectedDebugAndroidTest --continue

  package:
    name: Package and Upload
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/development'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x Flightwise/gradlew

    - name: Assemble release APK
      run: cd Flightwise && ./gradlew assembleRelease

    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: Flightwise/app/build/outputs/apk/release/app-release.apk