name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x Flightwise/gradlew

    - name: Build with Gradle
      run: Flightwise/gradlew build

    - name: Run Unit Tests
      run: Flightwise/gradlew test --continue

    - name: Run Lint
      run: Flightwise/gradlew lint

    - name: Run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: Nexus 6
        script: Flightwise/gradlew connectedAndroidTest --continue

    - name: Assemble Release
      if: github.ref == 'refs/heads/development'
      run: Flightwise/gradlew assembleRelease

    - name: Upload APK
      if: github.ref == 'refs/heads/development'
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
